Add back more of our disabled tests

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -275,67 +275,45 @@ aliases:
     name: Boot iPhone Simulator
     command: xcrun simctl boot "iPhone 5s" || true
 
-  - &boot-simulator-iphone-with-parallelism
-    name: Boot iPhone Simulator
-    command: |
-      if [ $((0 % CIRCLE_NODE_TOTAL)) -eq "$CIRCLE_NODE_INDEX" ]; then
-        xcrun simctl boot "iPhone 5s" || true
-      fi
-
-  - &boot-simulator-appletv-with-parallelism
+  - &boot-simulator-appletv
     name: Boot Apple TV Simulator
-    command: |
-      if [ $((1 % CIRCLE_NODE_TOTAL)) -eq "$CIRCLE_NODE_INDEX" ]; then
-        xcrun simctl boot "Apple TV" || true
-      fi
+    command: xcrun simctl boot "Apple TV" || true
 
-  - &run-objc-ios-tests-with-parallelism
+  - &run-objc-ios-tests
     name: iOS Test Suite
-    command: |
-      if [ $((0 % CIRCLE_NODE_TOTAL)) -eq "$CIRCLE_NODE_INDEX" ]; then
-        ./scripts/objc-test-ios.sh test
-      fi
+    command: ./scripts/objc-test-ios.sh test
 
-  - &run-objc-tvos-tests-with-parallelism
+  - &run-objc-tvos-tests
     name: tvOS Test Suite
-    command: |
-      if [ $((1 % CIRCLE_NODE_TOTAL)) -eq "$CIRCLE_NODE_INDEX" ]; then
-        ./scripts/objc-test-tvos.sh test
-      fi
+    command: ./scripts/objc-test-tvos.sh test
 
-  - &run-podspec-tests-with-parallelism
+  - &run-podspec-tests
     name: Test CocoaPods (Ignoring failures)
     command: |
-      if [ $((2 % CIRCLE_NODE_TOTAL)) -eq "$CIRCLE_NODE_INDEX" ]; then
-        echo 'The following step is known to be failing in master, and any failures will be ignored.'
-        scripts/circleci/exec_swallow_error.sh ./scripts/process-podspecs.sh
-      fi
+      echo 'The following step is known to be failing in master, and any failures will be ignored.'
+      scripts/circleci/exec_swallow_error.sh ./scripts/process-podspecs.sh
 
   - &run-e2e-tests
     name: End-to-End Test Suite
     command: node ./scripts/run-ci-e2e-tests.js --android --ios --tvos --js --retries 3;
 
   - &run-objc-ios-e2e-tests
-    name: iOS End-to-End Test Suite
-    command: |
-      node ./scripts/run-ci-e2e-tests.js --ios --retries 3;
-
-  - &run-objc-ios-e2e-tests-with-parallelism
     name: iOS End-to-End Test Suite (Ignoring failures)
     command: |
-      if [ $((0 % CIRCLE_NODE_TOTAL)) -eq "$CIRCLE_NODE_INDEX" ]; then
-        echo 'The following step is known to be failing in master, and any failures will be ignored.'
-        scripts/circleci/exec_swallow_error.sh node ./scripts/run-ci-e2e-tests.js --ios --retries 3;
-      fi
+      echo 'The following step is known to be failing in master, and any failures will be ignored.'
+      scripts/circleci/exec_swallow_error.sh node ./scripts/run-ci-e2e-tests.js --ios --retries 3;
 
-      - &run-objc-tvos-e2e-tests
-    name: tvOS End-to-End Test Suite
+  - &run-objc-tvos-e2e-tests
+    name: tvOS End-to-End Test Suite (Ignoring failures)
     command: |
-      node ./scripts/run-ci-e2e-tests.js --tvos --js --retries 3;
+      echo 'The following step is known to be failing in master, and any failures will be ignored.'
+      scripts/circleci/exec_swallow_error.sh node ./scripts/run-ci-e2e-tests.js --tvos --js --retries 3;
 
   - &run-android-e2e-tests
-    name: Android End-to-End Test Suite
-    command: node ./scripts/run-ci-e2e-tests.js --android --retries 3;
+    name: Android End-to-End Test Suite (Ignoring failures)
+    command:  |
+      echo 'The following step is known to be failing in master, and any failures will be ignored.'
+      scripts/circleci/exec_swallow_error.sh node ./scripts/run-ci-e2e-tests.js --android --retries 3;
 
   - &run-js-e2e-tests
     name: JavaScript End-to-End Test Suite
@@ -437,25 +415,24 @@ jobs:
   # Runs unit tests on iOS and Apple TV devices
   test_objc:
     <<: *macos_defaults
-    # Bump back to 3 whenever podspec tests are re-enabled
-    parallelism: 2
     steps:
       - attach_workspace:
           at: ~/react-native
 
-      - run: *boot-simulator-iphone-with-parallelism
-      - run: *boot-simulator-appletv-with-parallelism
+      - run: *boot-simulator-iphone
+      - run: *boot-simulator-appletv
       - run: *brew-install-watchman
 
-      - run: *run-objc-ios-tests-with-parallelism
-      - run: *run-objc-tvos-tests-with-parallelism
+      - run: *run-objc-ios-tests
+      - run: *run-objc-tvos-tests
 
       # The following are "disabled" - the steps will
       # still run, but failures will be ignored.
       # This is good for debugging flaky CI steps.
       # TODO: Reenable as soon as they are in working order.
-      - run: *run-podspec-tests-with-parallelism
-      - run: *run-objc-ios-e2e-tests-with-parallelism
+      - run: *run-podspec-tests
+      - run: *run-objc-ios-e2e-tests
+      - run: *run-objc-tvos-e2e-tests
 
       - store_test_results:
           path: ~/react-native/reports/junit
@@ -559,8 +536,11 @@ jobs:
       - run: *build-android-rntester-app
 
       # Run Android end-to-end tests
-      # Disabled
-      # - run: *run-android-e2e-tests
+      # The following are "disabled" - the steps will
+      # still run, but failures will be ignored.
+      # This is good for debugging flaky CI steps.
+      # TODO: Reenable as soon as they are in working order.
+      - run: *run-android-e2e-tests
 
       # Collect Results
       - run: *collect-android-test-results
