Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,11 +1,10 @@
 aliases:
   # Cache Management
-  - &restore-yarn-cache
+  - &restore-cache-yarn
     keys:
       - v1-yarn-{{ arch }}-{{ checksum "package.json" }}
-      # Fallback in case checksum fails
       - v1-yarn-{{ arch }}-
-  - &save-yarn-cache
+  - &save-cache-yarn
     paths:
       - node_modules
       - ~/.cache/yarn
@@ -14,7 +13,6 @@ aliases:
   - &restore-cache-analysis
     keys:
       - v1-analysis-dependencies-{{ arch }}-{{ checksum "package.json" }}{{ checksum "bots/package.json" }}
-      # Fallback in case checksum fails
       - v1-analysis-dependencies-{{ arch }}-
   - &save-cache-analysis
     paths:
@@ -25,20 +23,45 @@ aliases:
   - &restore-cache-android-packages
     keys:
       - v1-android-sdkmanager-packages-{{ arch }}-api-26-alpha-{{ checksum "scripts/circle-ci-android-setup.sh" }}
-      # Fallback in case checksum fails
       - v1-android-sdkmanager-packages-{{ arch }}-api-26-alpha-
   - &save-cache-android-packages
     paths:
       - /opt/android/sdk
     key: v1-android-sdkmanager-packages-{{ arch }}-api-26-alpha-{{ checksum "scripts/circle-ci-android-setup.sh" }}
 
+  - &restore-cache-gradle
+    keys:
+      - v1-gradle-{{ arch }}-{{ .Branch }}-{{ checksum "build.gradle" }}-{{ checksum "ReactAndroid/build.gradle" }}
+      # Fallback in case checksum fails
+      - v1-gradle-{{ arch }}-{{ .Branch }}-{{ checksum "build.gradle" }}-
+      - v1-gradle-{{ arch }}-{{ .Branch }}-
+      # Fallback in case this is a first-time run on a fork
+      - v1-gradle-{{ arch }}-master-
+  - &save-cache-gradle
+    paths:
+      - ~/.gradle
+    key: v1-gradle-{{ arch }}-{{ .Branch }}-{{ checksum "build.gradle" }}-{{ checksum "ReactAndroid/build.gradle" }}
+
+  - &restore-cache-apt
+    keys:
+      - v1-apt-{{ arch }}-{{ .Branch }}-{{ checksum "scripts/circleci/apt-get-android-deps.sh" }}
+      # Fallback in case checksum fails
+      - v1-apt-{{ arch }}-{{ .Branch }}-
+      # Fallback in case this is a first-time run on a fork
+      - v1-apt-{{ arch }}-master-
+  - &save-cache-apt
+    paths:
+      - ~/vendor/apt
+    key: v1-apt-{{ arch }}-{{ .Branch }}-{{ checksum "scripts/circleci/apt-get-android-deps.sh" }}
+
   - &restore-cache-ndk
     keys:
-      - v2-android-ndk-{{ arch }}-r10e-32-64
+      - v2-android-ndk-{{ arch }}-r10e-32-64-{{ checksum "scripts/circle-ci-android-setup.sh" }}
+      - v2-android-ndk-{{ arch }}-r10e-32-64-
   - &save-cache-ndk
     paths:
       - /opt/ndk
-    key: v2-android-ndk-{{ arch }}-r10e-32-64
+    key: v2-android-ndk-{{ arch }}-r10e-32-64-{{ checksum "scripts/circle-ci-android-setup.sh" }}
 
   - &restore-cache-buck
     keys:
@@ -56,6 +79,17 @@ aliases:
       - ~/watchman
     key: v1-watchman-{{ arch }}-v4.9.0
 
+  - &restore-cache-gradle-downloads
+    keys:
+      - v1-gradle-{{ arch }}-{{ checksum "ReactAndroid/build.gradle" }}-{{ checksum "scripts/circleci/gradle_download_deps.sh" }}
+      - v1-gradle-{{ arch }}-
+  - &save-cache-gradle-downloads
+    paths:
+      - ~/.gradle
+      - ReactAndroid/build/downloads
+      - ReactAndroid/build/third-party-ndk
+    key: v1-gradle-{{ arch }}-{{ checksum "ReactAndroid/build.gradle" }}-{{ checksum "scripts/circleci/gradle_download_deps.sh" }}
+
   # Branch Filtering
   - &filter-only-master-stable
     branches:
@@ -67,11 +101,6 @@ aliases:
     branches:
       only:
         - /.*-stable/
-
-  - &filter-only-master
-    branches:
-      only:
-        - master
 
   - &filter-ignore-gh-pages
     branches:
@@ -86,15 +115,16 @@ aliases:
 
   # Dependency Management
   - &install-ndk
-    |
-      source scripts/circle-ci-android-setup.sh && getAndroidNDK
+    name: Install Android NDK
+    command: source scripts/circle-ci-android-setup.sh && getAndroidNDK
 
   - &yarn
     |
       yarn install --non-interactive --cache-folder ~/.cache/yarn
 
   - &install-yarn
-    |
+    name: Install Yarn
+    command: |
       curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
       echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
       sudo apt-get update && sudo apt-get install yarn
@@ -104,7 +134,8 @@ aliases:
       npm install --no-package-lock --no-spin --no-progress
 
   - &install-buck
-    |
+    name: Install BUCK
+    command: |
       if [[ ! -e ~/buck ]]; then
         git clone https://github.com/facebook/buck.git ~/buck --branch v2018.02.16.01 --depth=1
       fi
@@ -112,7 +143,8 @@ aliases:
       buck --version
 
   - &install-node
-    |
+    name: Install Node
+    command: |
       curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
       sudo apt-get install -y nodejs
 
@@ -133,23 +165,30 @@ aliases:
       source $BASH_ENV
 
   - &install-android-packages
-    | 
-      source scripts/circle-ci-android-setup.sh && getAndroidSDK
+    name: Install Android SDK Packages
+    command: source scripts/circle-ci-android-setup.sh && getAndroidSDK
 
   - &install-android-build-dependencies
     name: Install Android Build Dependencies
-    command: |
-      sudo apt-get update -y
-      sudo apt-get install ant autoconf automake g++ gcc libqt5widgets5 lib32z1 lib32stdc++6  make maven python-dev python3-dev qml-module-qtquick-controls qtdeclarative5-dev file -y
+    command: ./scripts/circleci/apt-get-android-deps.sh
+
+  - &validate-android-sdk
+    name: Validate Android SDK Install
+    command: ./scripts/validate-android-sdk.sh
+
+  - &validate-android-test-env
+    name: Validate Android Test Environment
+    command: ./scripts/validate-android-test-env.sh
 
   # Test Definitions
   - &run-js-tests
     name: JavaScript Test Suite
     command: yarn test-ci
-    
+
+  # eslint sometimes runs into trouble generating the reports
   - &run-lint-checks
     name: Lint code
-    command: yarn lint --format junit -o ~/react-native/reports/junit/js-lint-results.xml
+    command: scripts/circleci/exec_swallow_error.sh yarn lint --format junit -o ~/react-native/reports/junit/js-lint-results.xml
     when: always
 
   - &run-flow-checks
@@ -157,17 +196,17 @@ aliases:
     command: yarn flow check
     when: always
 
-  - &run-license-checks
-    name: Check license
-    command: ./scripts/circleci/check_license.sh
+  - &run-sanity-checks
+    name: Sanity checks
+    command: |
+      ./scripts/circleci/check_license.sh
+      ./scripts/circleci/check_cache.sh
     when: always
 
-  - &test-coverage
-    name: Test coverage
-    command: |
-      yarn test --coverage --maxWorkers=2
-      cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
-
+  - &gradle-download-deps
+    name: Download C++ Dependencies
+    command: ./scripts/circleci/gradle_download_deps.sh
+    
   - &build-android-app
     name: Build Android App
     command: |
@@ -220,29 +259,21 @@ aliases:
     name: Initial Setup
     command: | 
       mkdir -p ~/react-native/reports/junit/
-
-  - &build-objc-ios-test-app
-    name: Build Objective-C iOS Test App
-    command: ./scripts/objc-test-ios.sh
   
   - &run-objc-ios-tests
-    name: Objective-C iOS Test Suite
+    name: iOS Test Suite
     command: ./scripts/objc-test-ios.sh test
 
-  - &build-objc-tvos-test-app
-    name: Build Objective-C tvOS Test App
-    command: ./scripts/objc-test-tvos.sh
-
   - &run-objc-tvos-tests
-    name: Objective-C tvOS Test Suite
+    name: tvOS Test Suite
     command: ./scripts/objc-test-tvos.sh test
 
   - &run-objc-ios-e2e-tests
-    name: Objective-C iOS End-to-End Test Suite
+    name: iOS End-to-End Test Suite
     command: node ./scripts/run-ci-e2e-tests.js --ios --js --retries 3;
 
   - &run-objc-tvos-e2e-tests
-    name: Objective-C tvOS End-to-End Test Suite
+    name: tvOS End-to-End Test Suite
     command: node ./scripts/run-ci-e2e-tests.js --tvos --js --retries 3;
 
 defaults: &defaults
@@ -252,6 +283,8 @@ js_defaults: &js_defaults
   <<: *defaults
   docker:
     - image: circleci/node:8
+  environment:
+    - PATH: "/opt/yarn/yarn-v1.5.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
 
 android_defaults: &android_defaults
   <<: *defaults
@@ -281,9 +314,12 @@ jobs:
       - checkout
       - run: *setup-artifacts
 
-      - restore-cache: *restore-yarn-cache
+      - restore-cache: *restore-cache-yarn
       - run: *yarn
-      - save-cache: *save-yarn-cache
+      - save-cache: *save-cache-yarn
+
+      # Basic checks against the checkout, cache...
+      - run: *run-sanity-checks
 
       - persist_to_workspace:
           root: .
@@ -299,11 +335,8 @@ jobs:
 
       - run: *run-lint-checks
       - run: *run-flow-checks
-      - run: *run-license-checks
 
       - store_test_results:
-          path: ~/react-native/reports/junit
-      - store_artifacts:
           path: ~/react-native/reports/junit
       - store_artifacts:
           path: ~/react-native/yarn.lock
@@ -319,8 +352,6 @@ jobs:
 
       - store_test_results:
           path: ~/react-native/reports/junit
-      - store_artifacts:
-          path: ~/react-native/reports/junit
 
   # Runs JavaScript tests on Node 6
   test_javascript_node6_compatibility:
@@ -331,102 +362,54 @@ jobs:
       - checkout
       - run: *setup-artifacts
 
-      - restore-cache: *restore-yarn-cache
+      - restore-cache: *restore-cache-yarn
       - run: *yarn
-      - save-cache: *save-yarn-cache
+      - save-cache: *save-cache-yarn
 
       - run: *run-js-tests
 
       - store_test_results:
           path: ~/react-native/reports/junit
-      - store_artifacts:
-          path: ~/react-native/reports/junit
-
-  # Test Coverage
-  test_coverage:
-    <<: *js_defaults
-    steps:
-      - attach_workspace:
-          at: ~/react-native
-    
-      - run: *test-coverage
-
-      - store_artifacts:
-          path: ~/react-native/coverage/
-
-  # Builds iOS test app
-  build_objc_ios_test_app:
-    <<: *macos_defaults
-    dependencies:
-      pre:
-        - xcrun instruments -w "iPhone 5s (11.1)" || true
-    steps:
-      - attach_workspace:
-          at: ~/react-native
-
-      - run: *build-objc-ios-test-app
 
   # Runs unit tests on iOS devices
-  test_objc_ios:
+  test_ios:
     <<: *macos_defaults
-    dependencies:
-      pre:
-        - xcrun instruments -w "iPhone 5s (11.1)" || true
     steps:
       - attach_workspace:
           at: ~/react-native
 
+      - run: xcrun instruments -w "iPhone 5s (11.1)" || true
+      - run: brew install watchman
       - run: *run-objc-ios-tests
 
       - store_test_results:
           path: ~/react-native/reports/junit
-      - store_artifacts:
-          path: ~/react-native/reports/junit
-
-  # Builds tvOS test app
-  build_objc_tvos_test_app:
-    <<: *macos_defaults
-    dependencies:
-      pre:
-        - xcrun instruments -w "Apple TV 1080p (11.1)" || true
-    steps:
-      - attach_workspace:
-          at: ~/react-native
-
-      - run: *build-objc-tvos-test-app
 
   # Runs unit tests on tvOS devices
-  test_objc_tvos:
+  test_tvos:
     <<: *macos_defaults
-    dependencies:
-      pre:
-        - xcrun instruments -w "Apple TV 1080p (11.1)" || true
     steps:
       - attach_workspace:
           at: ~/react-native
 
+      - run: xcrun instruments -w "Apple TV 1080p (11.1)" || true
+      - run: brew install watchman
       - run: *run-objc-tvos-tests
 
       - store_test_results:
           path: ~/react-native/reports/junit
-      - store_artifacts:
-          path: ~/react-native/reports/junit
 
   # Runs end to end tests
-  test_objc_ios_e2e:
+  test_ios_e2e:
     <<: *macos_defaults
-    dependencies:
-      pre:
-        - xcrun instruments -w "iPhone 5s (11.1)" || true
     steps:
       - attach_workspace:
           at: ~/react-native
 
+      - run: xcrun instruments -w "iPhone 5s (11.1)" || true
       - run: *run-objc-ios-e2e-tests
 
       - store_test_results:
-          path: ~/react-native/reports/junit
-      - store_artifacts:
           path: ~/react-native/reports/junit
 
   # Checks podspec
@@ -448,6 +431,7 @@ jobs:
       # Configure Android SDK and related dependencies
       - run: *configure-android-path
       - run: *install-android-build-dependencies
+
       - restore-cache: *restore-cache-android-packages
       - run: *install-android-packages
       - save-cache: *save-cache-android-packages
@@ -468,13 +452,16 @@ jobs:
       - run: buck fetch ReactAndroid/src/main/java/com/facebook/react/shell
       - run: buck fetch ReactAndroid/src/test/...
       - run: buck fetch ReactAndroid/src/androidTest/...
-      - run: ./gradlew :ReactAndroid:downloadBoost :ReactAndroid:downloadDoubleConversion :ReactAndroid:downloadFolly :ReactAndroid:downloadGlog :ReactAndroid:downloadJSCHeaders
+
+      - restore-cache: *restore-cache-gradle-downloads
+      - run: *gradle-download-deps
+      - save-cache: *save-cache-gradle-downloads
 
       - run: *install-node
       - run: *install-yarn
-      - restore-cache: *restore-yarn-cache
+      - restore-cache: *restore-cache-yarn
       - run: *yarn
-      - save-cache: *save-yarn-cache
+      - save-cache: *save-cache-yarn
       
       - run:
           name: Publish React Native Package
@@ -498,10 +485,15 @@ jobs:
 
       # Configure Android SDK and related dependencies
       - run: *configure-android-path
+      - restore-cache: *restore-cache-apt
       - run: *install-android-build-dependencies
+      - save-cache: *save-cache-apt
+
       - restore-cache: *restore-cache-android-packages
       - run: *install-android-packages
       - save-cache: *save-cache-android-packages
+
+      - run: *validate-android-sdk
 
       # Starting emulator in advance as it takes some time to boot.      
       - run: *create-avd
@@ -520,12 +512,17 @@ jobs:
       - run: *install-buck
       - save-cache: *save-cache-buck
 
+      - run: *validate-android-test-env
+
       - run: buck fetch ReactAndroid/src/test/java/com/facebook/react/modules
       - run: buck fetch ReactAndroid/src/main/java/com/facebook/react
       - run: buck fetch ReactAndroid/src/main/java/com/facebook/react/shell
       - run: buck fetch ReactAndroid/src/test/...
       - run: buck fetch ReactAndroid/src/androidTest/...
-      - run: ./gradlew :ReactAndroid:downloadBoost :ReactAndroid:downloadDoubleConversion :ReactAndroid:downloadFolly :ReactAndroid:downloadGlog :ReactAndroid:downloadJSCHeaders
+
+      - restore-cache: *restore-cache-gradle-downloads
+      - run: *gradle-download-deps
+      - save-cache: *save-cache-gradle-downloads
 
       # Build and compile
       - run: *build-android-app
@@ -537,7 +534,7 @@ jobs:
 
       # Wait for AVD to finish booting before running tests
       - run: *wait-for-avd
-            
+
       # Test Suite
       - run: *run-android-unit-tests
       - run: *run-android-instrumentation-tests
@@ -545,8 +542,6 @@ jobs:
       # post (always runs)
       - run: *collect-android-test-results
       - store_test_results:
-          path: ~/react-native/reports/junit
-      - store_artifacts:
           path: ~/react-native/reports/junit
 
 
@@ -588,7 +583,7 @@ jobs:
           command: |
             # GITHUB_TOKEN=eslint-bot public_repo access token
             if [ -n "$CIRCLE_PR_NUMBER" ]; then
-              cat <(echo eslint; yarn --silent lint --format=json; echo flow; yarn --silent flow check --json) | GITHUB_TOKEN="af6ef0d15709bc91d""06a6217a5a826a226fb57b7" CI_USER=$CIRCLE_PROJECT_USERNAME CI_REPO=$CIRCLE_PROJECT_REPONAME PULL_REQUEST_NUMBER=$CIRCLE_PR_NUMBER node bots/code-analysis-bot.js
+              GITHUB_TOKEN="af6ef0d15709bc91d""06a6217a5a826a226fb57b7" CI_USER=$CIRCLE_PROJECT_USERNAME CI_REPO=$CIRCLE_PROJECT_REPONAME PULL_REQUEST_NUMBER=$CIRCLE_PR_NUMBER scripts/circleci/analyze_code.sh
             else
               echo "Skipping code analysis."            
             fi
@@ -627,28 +622,22 @@ workflows:
           requires:
             - checkout_code
 
-      # Build iOS & tvOS test apps
-      - build_objc_ios_test_app:
+      # Test iOS & tvOS
+      - test_ios:
           filters: *filter-ignore-gh-pages
           requires:
             - checkout_code
-      - build_objc_tvos_test_app:
+      - test_tvos:
           filters: *filter-ignore-gh-pages
           requires:
             - checkout_code
 
       # End-to-end tests
-      - test_objc_ios_e2e:
+      - test_ios_e2e:
           filters: *filter-ignore-gh-pages
           requires:
             - checkout_code
 
-      # Collect test coverage (only on master)
-      - test_coverage:
-          filters: *filter-only-master
-          requires:
-            - checkout_code
-            
   # Only runs on PRs
   analyze:
     jobs:
@@ -686,15 +675,6 @@ workflows:
 
   #     # The following were DISABLED because they have not run since 
   #     # the migration from Travis, and they have broken since then,
-  #     # Test iOS & tvOS
-  #     - test_objc_ios:
-  #         filters: *filter-ignore-gh-pages
-  #         requires:
-  #           - checkout_code
-  #     - test_objc_tvos:
-  #         filters: *filter-ignore-gh-pages
-  #         requires:
-  #           - checkout_code
   #     # CocoaPods
   #     - test_podspec:
   #         filters: *filter-ignore-gh-pages
