ci(0.76): "update to nx 21" followup fixes (#2579)

diff --git a/.ado/jobs/npm-publish.yml b/.ado/jobs/npm-publish.yml
--- a/.ado/jobs/npm-publish.yml
+++ b/.ado/jobs/npm-publish.yml
@@ -24,7 +24,11 @@ jobs:
     - template: /.ado/templates/configure-git.yml@self
 
     - script: |
-        PUBLISH_TAG=$(jq -r '.release.version.generatorOptions.currentVersionResolverMetadata.tag' nx.json)
+        PUBLISH_TAG=$(jq -r '.release.version.versionActionsOptions.currentVersionResolverMetadata.tag' nx.json)
+        if [ -z "$PUBLISH_TAG" ] || [ "$PUBLISH_TAG" = "null" ]; then
+          echo "Error: Failed to read publish tag from nx.json"
+          exit 1
+        fi
         echo "##vso[task.setvariable variable=publishTag]$PUBLISH_TAG"
         echo "Using publish tag from nx.json: $PUBLISH_TAG"
       displayName: Read publish tag from nx.json
@@ -61,7 +65,12 @@ jobs:
 
       - script: |
           if [[ -f .rnm-publish ]]; then
-            yarn nx release publish --tag ${{ parameters['publishTag'] }} --excludeTaskDependencies 
+            # https://github.com/microsoft/react-native-macos/issues/2580
+            # `nx release publish` gets confused by the output of RNM's prepack script.
+            # Let's call `yarn npm publish` directly instead on the packages we want to publish.
+            # yarn nx release publish --tag ${{ parameters['publishTag'] }} --excludeTaskDependencies
+            yarn ./packages/virtualized-lists npm publish --tag ${{ parameters['publishTag'] }}
+            yarn ./packages/react-native npm publish --tag ${{ parameters['publishTag'] }}
           fi
         displayName: Publish packages
         condition: and(succeeded(), eq(variables['publish_react_native_macos'], '1'))
